
During the deployment, you may need to use the following **AWS CLI** commands.   

eb init -p python-3.6 django-tally   
eb create django-tally   
eb status   
eb deploy   
eb open   
eb logs    
eb config   
eb terminate django-tally   

```
(base) PS D:\github\django-tally> eb init -p python-3.6 django-tally-ds
Application django-tally-ds has been created.
(base) PS D:\github\django-tally> eb create django-tally-ds
Creating application version archive "app-e558-200109_080738".
Uploading: [##################################################] 100% Done...
Environment details for: django-tally-ds
  Application name: django-tally-ds
  Region: us-west-2
  Deployed Version: app-e558-200109_080738
  Environment ID: e-xfghfagpvt
  Platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running on 64bit Amazon Linux/2.9.4
  Tier: WebServer-Standard-1.0
  CNAME: UNKNOWN
  Updated: 2020-01-09 14:08:02.102000+00:00
Printing Status:
2020-01-09 14:08:00    INFO    createEnvironment is starting.
2020-01-09 14:08:02    INFO    Using elasticbeanstalk-us-west-2-322429114750 as Amazon S3 storage bucket for environment data.
2020-01-09 14:08:24    INFO    Created security group named: sg-0092a008bdae309cd
2020-01-09 14:08:24    INFO    Created load balancer named: awseb-e-x-AWSEBLoa-1I2BXIAG1O89B
2020-01-09 14:08:41    INFO    Created security group named: awseb-e-xfghfagpvt-stack-AWSEBSecurityGroup-1FDROC7IN2D3X
2020-01-09 14:08:41    INFO    Created Auto Scaling launch configuration named: awseb-e-xfghfagpvt-stack-AWSEBAutoScalingLaunchConfiguration-1GYS7VL5DV48U
2020-01-09 14:09:43    INFO    Created Auto Scaling group named: awseb-e-xfghfagpvt-stack-AWSEBAutoScalingGroup-1A6Q0K28CVNY1
2020-01-09 14:09:43    INFO    Waiting for EC2 instances to launch. This may take a few minutes.
2020-01-09 14:09:43    INFO    Created Auto Scaling group policy named: arn:aws:autoscaling:us-west-2:322429114750:scalingPolicy:3276b88e-171d-4095-8798-4e6897083d00:autoScalingGroupName/awseb-e-xfghfagpvt-stack-AWSEBAutoScalingGroup-1A6Q0K28CVNY1:policyName/awseb-e-xfghfagpvt-stack-AWSEBAutoScalingScaleUpPolicy-NMZJCI0KP5HG
2020-01-09 14:09:43    INFO    Created Auto Scaling group policy named: arn:aws:autoscaling:us-west-2:322429114750:scalingPolicy:ba1d3cad-1a24-4314-99fc-e385d179cf68:autoScalingGroupName/awseb-e-xfghfagpvt-stack-AWSEBAutoScalingGroup-1A6Q0K28CVNY1:policyName/awseb-e-xfghfagpvt-stack-AWSEBAutoScalingScaleDownPolicy-NIG6UPM8MMB0
2020-01-09 14:09:43    INFO    Created CloudWatch alarm named: awseb-e-xfghfagpvt-stack-AWSEBCloudwatchAlarmLow-M951720D84XJ
2020-01-09 14:09:43    INFO    Created CloudWatch alarm named: awseb-e-xfghfagpvt-stack-AWSEBCloudwatchAlarmHigh-1EKIK3BRJ29AS
2020-01-09 14:11:32    INFO    Application available at django-tally-ds.cz5ymmder6.us-west-2.elasticbeanstalk.com.
2020-01-09 14:11:33    INFO    Successfully launched environment: django-tally-ds

(base) PS D:\github\django-tally> eb status
Environment details for: django-tally-ds
  Application name: django-tally-ds
  Region: us-west-2
  Deployed Version: app-e558-200109_080738
  Environment ID: e-xfghfagpvt
  Platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running on 64bit Amazon Linux/2.9.4
  Tier: WebServer-Standard-1.0
  CNAME: django-tally-ds.cz5ymmder6.us-west-2.elasticbeanstalk.com
  Updated: 2020-01-09 14:11:33.190000+00:00
  Status: Ready
  Health: Green
(base) PS D:\github\django-tally> eb deploy
Creating application version archive "app-3910-200109_081527".
Uploading: [##################################################] 100% Done...
2020-01-09 14:15:50    INFO    Environment update is starting.
2020-01-09 14:15:53    INFO    Deploying new version to instance(s).
2020-01-09 14:16:33    INFO    New application version was deployed to running EC2 instances.
2020-01-09 14:16:33    INFO    Environment update completed successfully.

(base) PS D:\github\django-tally> eb open
(base) PS D:\github\django-tally> eb logs
Retrieving logs...
============= i-0ea51a5d421b8314b ==============
-------------------------------------
/var/log/httpd/error_log
-------------------------------------
[Thu Jan 09 14:09:23.328832 2020] [suexec:notice] [pid 3121] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jan 09 14:09:23.343899 2020] [http2:warn] [pid 3121] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Thu Jan 09 14:09:23.343910 2020] [http2:warn] [pid 3121] AH02951: mod_ssl does not seem to be enabled
[Thu Jan 09 14:09:23.344340 2020] [lbmethod_heartbeat:notice] [pid 3121] AH02282: No slotmem from mod_heartmonitor
[Thu Jan 09 14:09:23.344383 2020] [:warn] [pid 3121] mod_wsgi: Compiled for Python/3.6.2.
[Thu Jan 09 14:09:23.344386 2020] [:warn] [pid 3121] mod_wsgi: Runtime using Python/3.6.8.
[Thu Jan 09 14:09:23.346141 2020] [mpm_prefork:notice] [pid 3121] AH00163: Apache/2.4.41 (Amazon) mod_wsgi/3.5 Python/3.6.8 configured -- resuming normal operations
[Thu Jan 09 14:09:23.346154 2020] [core:notice] [pid 3121] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jan 09 14:10:54.429284 2020] [mpm_prefork:notice] [pid 3121] AH00169: caught SIGTERM, shutting down
[Thu Jan 09 14:10:55.548543 2020] [suexec:notice] [pid 3409] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Jan 09 14:10:55.563223 2020] [so:warn] [pid 3409] AH01574: module wsgi_module is already loaded, skipping
[Thu Jan 09 14:10:55.564967 2020] [http2:warn] [pid 3409] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Thu Jan 09 14:10:55.564977 2020] [http2:warn] [pid 3409] AH02951: mod_ssl does not seem to be enabled
[Thu Jan 09 14:10:55.565477 2020] [lbmethod_heartbeat:notice] [pid 3409] AH02282: No slotmem from mod_heartmonitor
[Thu Jan 09 14:10:55.565534 2020] [:warn] [pid 3409] mod_wsgi: Compiled for Python/3.6.2.
[Thu Jan 09 14:10:55.565538 2020] [:warn] [pid 3409] mod_wsgi: Runtime using Python/3.6.8.
[Thu Jan 09 14:10:55.567580 2020] [mpm_prefork:notice] [pid 3409] AH00163: Apache/2.4.41 (Amazon) mod_wsgi/3.5 Python/3.6.8 configured -- resuming normal operations
[Thu Jan 09 14:10:55.567595 2020] [core:notice] [pid 3409] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Jan 09 14:12:02.342350 2020] [core:error] [pid 3417] [client 127.0.0.1:46772] Script timed out before returning headers: wsgi.py
[Thu Jan 09 14:12:06.343190 2020] [core:error] [pid 3418] [client 127.0.0.1:46774] Script timed out before returning headers: wsgi.py
[Thu Jan 09 14:12:10.346828 2020] [core:error] [pid 3419] [client 127.0.0.1:46776] Script timed out before returning headers: wsgi.py
```

### [core:error] [pid 3419] [client 127.0.0.1:46776] Script timed out before returning headers: wsgi.py

https://stackoverflow.com/questions/55173639/script-timed-out-before-returning-headers-wsgi-py-django-on-elastic-beanstalk   
Script timed out before returning headers: wsgi.py - Django on Elastic Beanstalk   
Asked 10 months ago   

https://stackoverflow.com/questions/52020221/django-apache-coreerror-pid-10696-client-ip35768-script-timed-out    
So the issue was related to mod_wsgi library. Once I compiled mod_wsgi most recent version from source it worked perfectly! Instructions are available on their official docs: https://modwsgi.readthedocs.io/en/develop/user-guides/quick-installation-guide.html  

## This is the solution  
https://stackoverflow.com/questions/41812497/aws-elastic-beanstalk-script-timed-out-before-returning-headers-application-p/41855346    
The @user2752159's answer highlights the issue however I am going to add this to show how to overcome this issue in the context of AWS Beanstalk (ie. if a new instance or you deploy more code then the problem will remain fixed, rather than having to ssh into the box each time to modify wsgi.conf). 
```
nano .ebextensions/<some_name>.config 

# add the following to <some_name>.config 
files:
  "/etc/httpd/conf.d/wsgi_custom.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      WSGIApplicationGroup %{GLOBAL}

# add to git
git add .ebextensions/<some_name>.config
git commit -m 'message here'

# deploy to beanstalk
eb deploy
```  

```
Variable	Value
CONTEXT_DOCUMENT_ROOT	
'/var/www/html'
CONTEXT_PREFIX	
''
CSRF_COOKIE	
'hvPnevR32ehp5Qk4SckWhEAuESuImunqLwkgtpXlV26SOjLI55osbJnJz75rNOuo'
DOCUMENT_ROOT	
'/var/www/html'
GATEWAY_INTERFACE	
'CGI/1.1'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
HTTP_ACCEPT_ENCODING	
'gzip, deflate'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.9'
HTTP_CONNECTION	
'keep-alive'
HTTP_COOKIE	
'csrftoken=hvPnevR32ehp5Qk4SckWhEAuESuImunqLwkgtpXlV26SOjLI55osbJnJz75rNOuo'
HTTP_DNT	
'1'
HTTP_HOST	
'django-tally-ds.cz5ymmder6.us-west-2.elasticbeanstalk.com'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like '
 'Gecko) Chrome/79.0.3945.88 Safari/537.36')
HTTP_X_FORWARDED_FOR	
'99.100.99.240'
HTTP_X_FORWARDED_PORT	
'80'
HTTP_X_FORWARDED_PROTO	
'http'
PATH_INFO	
'/yelp/Iq7NqQD-sESu3vr9iEGuTA'
PATH_TRANSLATED	
'/opt/python/current/app/tally/wsgi.py/yelp/Iq7NqQD-sESu3vr9iEGuTA'
QUERY_STRING	
'viztype=1'
REMOTE_ADDR	
'172.31.49.6'
REMOTE_PORT	
'57354'
REQUEST_METHOD	
'GET'
REQUEST_SCHEME	
'http'
REQUEST_URI	
'/yelp/Iq7NqQD-sESu3vr9iEGuTA?viztype=1'
SCRIPT_FILENAME	
'/opt/python/current/app/tally/wsgi.py'
SCRIPT_NAME	
''
SERVER_ADDR	
'172.31.50.159'
SERVER_ADMIN	
'root@localhost'
SERVER_NAME	
'django-tally-ds.cz5ymmder6.us-west-2.elasticbeanstalk.com'
SERVER_PORT	
'80'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SIGNATURE	
''
SERVER_SOFTWARE	
'Apache/2.4.41 (Amazon) mod_wsgi/3.5 Python/3.6.8'
mod_wsgi.application_group	
''
mod_wsgi.callable_object	
'application'
mod_wsgi.enable_sendfile	
'0'
mod_wsgi.handler_script	
''
mod_wsgi.input_chunked	
'0'
mod_wsgi.listener_host	
''
mod_wsgi.listener_port	
'80'
mod_wsgi.process_group	
'wsgi'
mod_wsgi.queue_start	
'1578580538261270'
mod_wsgi.request_handler	
'wsgi-script'
mod_wsgi.script_reloading	
'1'
mod_wsgi.version	
(3, 5)
wsgi.errors	
<_io.TextIOWrapper encoding='utf-8'>
wsgi.file_wrapper	
''
wsgi.input	
<mod_wsgi.Input object at 0x7fa96a9adb70>
wsgi.multiprocess	
True
wsgi.multithread	
True
wsgi.run_once	
False
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
```

## Issue 
```
UnicodeDecodeError at /yelp/Iq7NqQD-sESu3vr9iEGuTA
'utf-8' codec can't decode byte 0xde in position 0: invalid continuation byte
Request Method:	GET
Request URL:	http://django-tally-ds.cz5ymmder6.us-west-2.elasticbeanstalk.com/yelp/Iq7NqQD-sESu3vr9iEGuTA?viztype=1
Django Version:	3.0.2
Exception Type:	UnicodeDecodeError
Exception Value:	
'utf-8' codec can't decode byte 0xde in position 0: invalid continuation byte
Exception Location:	_unpacker.pyx in srsly.msgpack._unpacker.unpackb, line 191
Python Executable:	/opt/python/run/venv/bin/python3
Python Version:	3.6.8
Python Path:	
['/opt/python/current/app',
 '',
 '/opt/python/run/venv/local/lib64/python3.6/site-packages',
 '/opt/python/run/venv/local/lib/python3.6/site-packages',
 '/opt/python/run/venv/lib64/python3.6',
 '/opt/python/run/venv/lib/python3.6',
 '/opt/python/run/venv/lib64/python3.6/site-packages',
 '/opt/python/run/venv/lib/python3.6/site-packages',
 '/opt/python/run/venv/lib64/python3.6/lib-dynload',
 '/usr/lib64/python3.6',
 '/usr/lib/python3.6']
Server time:	Thu, 9 Jan 2020 08:35:39 -0600
```
【Solution】      
The error happened at `nlp = space.load("en_core_web_sm").   
Windows 10 has this issue, while Mac doesn't.     